<?php

namespace Silvanus\ChainsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrustedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrustedRepository extends EntityRepository
{
}
