firewallrules:
    pattern:  /list/{chain_id}/{message}
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:index", message: '' }

firewallrules_show:
    pattern:  /{id}/show
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:show" }

firewallrules_new:
    pattern:  /new/{chain_id}
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:new" }

firewallrules_create:
    pattern:  /create/{chain_id}
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:create" }
    requirements: { _method: post|get }

firewallrules_edit:
    pattern:  /{id}/{chain_id}/edit
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:edit" }

firewallrules_update:
    pattern:  /{id}/{chain_id}/update
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:update" }
    requirements: { _method: post|put }

firewallrules_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:delete" }
    requirements: { _method: post|delete|get }
