firewallrules:
    pattern:  /
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:index" }

firewallrules_show:
    pattern:  /{id}/show
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:show" }

firewallrules_new:
    pattern:  /new
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:new" }

firewallrules_create:
    pattern:  /create
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:create" }
    requirements: { _method: post }

firewallrules_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:edit" }

firewallrules_update:
    pattern:  /{id}/update
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:update" }
    requirements: { _method: post|put }

firewallrules_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:delete" }
    requirements: { _method: post|delete }
