firewallrules:
    pattern:  /list/{id_chain}/{message}
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:index", message: '' }

firewallrules_show:
    pattern:  /{id}/show
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:show" }

firewallrules_new:
    pattern:  /new/{id_chain}
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:new" }

firewallrules_create:
    pattern:  /create/{id_chain}
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:create" }
    requirements: { _method: post|get }

firewallrules_edit:
    pattern:  /{id}/{id_chain}/edit
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:edit" }

firewallrules_update:
    pattern:  /{id}/{id_chain}/update
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:update" }
    requirements: { _method: post|put }

firewallrules_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:delete" }
    requirements: { _method: post|delete|get }

firewallrules_easy_new:
    pattern:  /easy/new/{id_chain}
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:easynew" }
    requirements: { _method: post|delete|get }

firewallrules_easy_create:
    pattern:  /easy/create/{id_chain}
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:easycreate" }
    requirements: { _method: post|delete|get }

firewallrules_easy_edit:
    pattern:  /easy/edit/{id}/{id_chain}
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:easyedit" }

firewallrules_easy_update:
    pattern:  /easy/update/{id}/{id_chain}
    defaults: { _controller: "SilvanusFirewallRulesBundle:FirewallRules:easyupdate" }
