silvanus_frontend:
    resource: "@SilvanusFrontendBundle/Resources/config/routing.yml"
    prefix:   /

silvanus_chains:
    resource: "@SilvanusChainsBundle/Resources/config/routing.yml"
    prefix:   /

silvanus_sync:
    resource: "@SilvanusSyncBundle/Resources/config/routing.yml"
    prefix:   /


silvanus_firewall_rules:
    resource: "@SilvanusFirewallRulesBundle/Resources/config/routing.yml"
    prefix:   /

