security:
    encoders:
        #~ Symfony\Component\Security\Core\User\User: plaintext
        Silvanus\SecurityBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        #~ in_memory:
            #~ memory:
                #~ users:
                    #~ user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    #~ admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

        users:
            entity: { class: SilvanusSecurityBundle:User, property: username }

    firewalls:
        dev:
            provider: users
            pattern:  ^/
            security: true
            anonymous: ~
            form_login:
                login_path:  /security/login
                check_path:  /security/login_check
                always_use_default_target_path: true
                default_target_path: /home
            logout:
                path: /security/logout
                target: /

        secured_area:
            provider: users
            pattern:  ^/
            security: true
            anonymous: ~
            form_login:
                login_path:  /security/login
                check_path:  /security/login_check
                always_use_default_target_path: true
                default_target_path: /home
                
            logout:
                path: /security/logout
                target: /

    access_control:
        - { path: ^/home, roles: ROLE_ADMIN }
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY } 
