<?php

namespace Silvanus\SyncBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SyncRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SyncRepository extends EntityRepository
{
}
