<?php

namespace Silvanus\FirewallRulesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FirewallRulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirewallRulesRepository extends EntityRepository
{
}
