<?php

namespace Silvanus\FirewallRulesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RulesSyncStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RulesSyncStatusRepository extends EntityRepository
{
}
