<?php

namespace Silvanus\FirewallRulesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TransportProtocolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransportProtocolRepository extends EntityRepository
{
}
